volumes:
  postgres_data:
  static:

services:
  db:
    restart: always
    image: postgres:13
    env_file:
      - './.env'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    build: ./app
    command: bash -c "alembic upgrade head && uvicorn app.main:app --proxy-headers --root-path /api --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - static:/static/
    env_file:
      - ./app/.env.prod
    depends_on:
      - db


  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/src:/app
  #     - static:/static/
  #   ports:
  #     - 3000:3000


  nginx:
    image: nginx:alpine
    volumes:
      # - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/src/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    ports:
      - 80:80
    depends_on:
      - backend
    #   - frontend
