"""add user name

Revision ID: ab67cc00365f
Revises: 795a54ad9090
Create Date: 2024-08-10 09:03:40.992551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab67cc00365f'
down_revision: Union[str, None] = '795a54ad9090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('destroy_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('secret', schema=None) as batch_op:
        batch_op.drop_column('destroy_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
